WebApplication1/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using businessLayer.Dtos.Item;
using businessLayer.IServices;
using DataAccessLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1
{
    [Authorize(Roles ="admin")]
    public class ItemsController : Controller
    {
        private readonly IItemService _ItemService;

        public ItemsController(IItemService ItemServiceItem)
        {
            _ItemService = ItemServiceItem;
        }

        // GET: Items
        public async Task<IActionResult> Index()

        {
            var res = await  _ItemService.GetItems();
            List <ItemReadDto> list = res.ToList();

            return                      View(list);
                      //list.Count>0  ?  Problem("Entity set 'WebApplication1ItemService.Item'  is null.");
        }


        // GET: Items/Create
        public IActionResult Create()
        {
            return View(new ItemCreateDto());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind(include: "Name")] ItemCreateDto itemdDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _ItemService.CreateItem(itemdDTO);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception)
                {

                    return RedirectToAction("BadRequest", "Default");
                }
            }
            return View(itemdDTO);
        }




    }
}

WebApplication1/Views/Items/Create.cshtml
@model businessLayer.Dtos.Item.ItemCreateDto

@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
       
    ViewData["Title"] = "Create";
}

<h1>Create Item</h1>

<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Create" asp-controller="Items" method="post">
            @Html.AntiForgeryToken()

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label" > Item Name</label>
                <input asp-for="Name" class="form-control" name="Name" required id="Name" />
                <span asp-validation-for="Name" data-valmsg-for="Name"
                      data-valmsg-replace="true" class="text-danger"></span>
            </div>
   <br />
   <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");
    }
}

WebApplication1/Views/Items/Index.cshtml
@model IEnumerable<businessLayer.Dtos.Item.ItemReadDto>

@{
    Layout = "~/Pages/Shared/_Layout.cshtml";

    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
         
          
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
         
           
        </tr>
}
    </tbody>
</table>