WebApplication1/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using businessLayer.Dtos.Item;
using businessLayer.Dtos.Order;
using businessLayer.IServices;
using DataAccessLayer;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1
{
    [Authorize(Roles = "Employee")]

    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IItemService _itemService;

        public OrdersController(IOrderService ordrServiceItem,IItemService itemService )
        {
            _orderService = ordrServiceItem;
            this._itemService = itemService;
        }

        // GET: Items
        //public async Task<IActionResult> Index()

        //{
        //    List <ItemReadDto> list = _orderService.GetItems().ToList();

        //    return                      View(list);
        //              //list.Count>0  ?  Problem("Entity set 'WebApplication1ItemService.Item'  is null.");
        //}


        // GET: Items/Create
        public async Task<IActionResult>   Create()
        {
            var items = await _itemService.GetItems();

            ViewBag.Items = new SelectList(items.ToList(), "Id", "Name");

            return View(new OrderCreateDto());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind(include: "ItemId,count,price")] OrderCreateDto orderDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ItemReadDto item = await this._itemService.GetItemById(orderDTO.ItemId);

                    if (item.TotalCount >= orderDTO.count)
                    {
                        await _orderService.CreateOrder(orderDTO);

                        return RedirectToAction("Success", "Default");
                    }

                }
                catch (Exception)
                {

                    return RedirectToAction("BadRequest", "Default");

                }


            }
            var items = await _itemService.GetItems();
            ViewBag.Items = new SelectList(items.ToList(), "Id", "Name",orderDTO.ItemId);

            return View(orderDTO);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<decimal> GetTotalCountOfItem([FromBody] OrderCreateDto ord)
        {

            try
            {
                if (ord != null && ord.ItemId > 0)
                {
                    ItemReadDto item = await this._itemService.GetItemById(ord.ItemId);
                    return item.TotalCount;

                }
                return 0;
            }
            catch (Exception)
            {

                return 0;
            }

        }


    }
}

WebApplication1/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using businessLayer.Dtos.Request;
using businessLayer.IServices;
using DataAccessLayer;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1
{
    [Authorize(Roles = "Employee")]

    public class RequestsController : Controller
    {
        private readonly IRequestService _requestService;
        private readonly IItemService _itemService;

        public RequestsController(IRequestService RequestServiceRequest,IItemService itemService)
        {
            _requestService = RequestServiceRequest;
            this._itemService = itemService;
        }

        // GET: Requests
        //public async Task<IActionResult> Index()

        //{
        //    List <RequestReadDto> list = _requestService.GetRequests().ToList();

        //    return                      View(list);
        //              //list.Count>0  ?  Problem("Entity set 'WebApplication1RequestService.Request'  is null.");
        //}


        // GET: Requests/Create
        public async Task<IActionResult> Create()
        {
            var items = await _itemService.GetItems();

            ViewBag.Items = new SelectList(items.ToList(), "Id", "Name");



            return View(new RequestCreateDto());
        }
 






        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(include: "ItemId,count,price")] RequestCreateDto RequestdDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _requestService.CreateRequest(RequestdDTO);

                    return RedirectToAction("Success", "Default");
                }

            }
            catch (Exception)
            {
                return RedirectToAction("BadRequest", "Default");


            }
            var items = await _itemService.GetItems();

            ViewBag.Items = new SelectList(items.ToList(), "Id", "Name",RequestdDTO.ItemId);
            return View(RequestdDTO);
        }




    }
}

WebApplication1/Views/Orders/Create.cshtml
@model businessLayer.Dtos.Order.OrderCreateDto
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create";
}

<h1>Sell Item  </h1>

<hr />
<div class="row">
    <div class="col-md-4">

        <form asp-action="Create" asp-controller="Requests" method="post">
            @Html.AntiForgeryToken()

            <div asp-validation-summary="ModelOnly" class="text-danger"  ></div>

            <div class="form-group">
                <label asp-for="ItemId" class="control-label"> Select Item</label>
@*                <select asp-for="ItemId" class="form-control" asp-items="@ViewBag.Items" name="ItemId" id="ItemId" />
*@
                @Html.DropDownList(expression: "ItemId",selectList: (IEnumerable
                <SelectListItem>)ViewData["Items"] ,new { @class = "form-control required" ,@id="ItemId"} )
                <span asp-validation-for="ItemId" class="text-danger"></span>

            </div>
      
            <div class="form-group">
                <label asp-for="count" class="control-label">Count</label>
                <input type="number" asp-for="count" class="form-control" name="count" id="count" required />
                <span asp-validation-for="count" data-valmsg-for="count" 
                      data-valmsg-replace="true" class="text-danger"></span>
                          <span   id="CountValidation"
                      class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label">Price </label>
                <input type="number" asp-for="price" class="form-control" name="price" id="price" required />
                <span asp-validation-for="price" data-valmsg-for="count"
                      data-valmsg-replace="true" class="text-danger"></span>
            </div>
            <br />
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>






@section Scripts {
    @{
        await Html.RenderPartialAsync("~/Views/Shared/_ValidationScriptsPartial.cshtml");

     
    }

    <script>

        $('#count').on("change", function () {
            checkCount();
        });

        $('#ItemId').on("change", function () {


            checkCount();
        });


        function checkCount(){

            var id = $('#ItemId').val();
            var selectedCount = $('#count').val();

            var obj = { "ItemId": id, "count": selectedCount }




            $.ajax({
                url: 'GetTotalCountOfItem',
                type: "POST",
                data: JSON.stringify(obj),

                contentType: "application/json",
                success: function (result) {

                    if (result < selectedCount &&  selectedCount != 0 && selectedCount != "" && id != 0 && id != "") {
                        $("#CountValidation").text("Selected Count Should Not exceed store Count")


                    }
                    else {
                        $("#CountValidation").text("")

                    }
                },
                error: function () {
                    alert(result);

                }
            });
        }
    </script>


}

WebApplication1/Views/Orders/Index.cshtml
@*@model IEnumerable<WebApplication1.Request>

@{
    Layout = "~/Pages/Shared/_Layout.cshtml";

    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.count)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
        
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
         
        </tr>
}
    </tbody>
</table>
*@